---
- hosts: all
  gather_facts: no
  vars:
    user: feycot
    php_version: '7.3'
    distr_name: bionic
  become: yes
  tasks:
    - name: Update repositories cache and install prerequisites
      apt: 
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present 
        update_cache: yes
    - import_tasks: playbooks/install_docker.yml
    - import_tasks: playbooks/install_php.yml