- name: add Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distr_name }} stable
    state: present
  tags: docker

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-compose']
    state: present
    update_cache: yes
  tags: docker

- name: Add user '{{ user }}' to group docker
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  tags: docker
