- name: add Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-compose']
    state: present
    update_cache: yes
- name: Add user '{{ user }}' to group docker
  user:
    name: '{{ user }}'
    groups: docker
    append: yes